 
version: '3.5'

services:
  api:
    container_name: payment-service
    build: .
    environment:
      DB_NAME: user_db
      DB_USER: admin
      DB_PASS: admin
      GATEWAY_PATH: http://api-gateway:5000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - 8009:8009
    networks: 
      - qr-comer
      - default
    
volumes:
  pgdata:
    driver: local

networks: 
  qr-comer:
    external:
      name: qr-comer
